def getGMLIDs(self, shapefile, attribute, value):
    """
    This function returns the gmlID associated with a particular attribute value.
    """
    tuples = self.getTuples(shapefile, attribute)
    return self._getFilterID(tuples, value)

def getTuples(self, shapefile, attribute):
    """
    Will return the dictionary tuples only.
    """
    return self.getValues(shapefile, attribute, getTuples='only')

def _getFilterID(self,tuples, value):
    """
    Given a the tuples generated by getTuples and a value, will return a list of gmlIDs
    associated with the value specified.
    """
    value = str(value)
    filterID = []
    for item in tuples:
        if item[0] == value:
            filterID.append(item[1])
    if filterID==[]:
        raise Exception('Feature attribute value %s was not found in the feature collection.' % value)
    return filterID
